server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    max-connections: 2000
  port: 8083
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/isly?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
    servlet:
      load-on-startup: 1
#    static-path-pattern: /
  resources:
    static-locations: classpath:/static/



#springdoc:
#  api-docs:
#    enabled: true
#    path: /doc-api.html
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: on

